[ClassVersion("1.0.0.0"), FriendlyName("MdeDefenderMode")]
class MdeDefenderMode : OMI_BaseResource
{
    [Key] string Name;
    [Required, ValueMap{"Active", "Passive"}, Values{"Active", "Passive"}] string Mode;
};